### ISSUE TITLE
Can't delete *.dbt file after creation

### ISSUE THREAD

**Issue by ChuichenkoKCK** [jferard/JxBase#13] opened 2021-05-28 14:11 UTC
If you try to delete *.dbf and *.dbt file, after line dbfWriter.close() in [WriterWithMemoIT](https://github.com/jferard/JxBase/blob/master/src/test/java/com/github/jferard/jxbase/it/WriterWithMemoIT.java) , you will find that you can not delete *.dbt file, "because it used by another process". As i can see it happens because MemoWriter is not closed during dbfWriter.close()

**Comment by jferard** [comment] 2021-05-28 14:57
Hi. Thanks for the issue. I'll have a look as soon as possible.

**Comment by jferard** [comment] 2021-05-28 20:04
@ChuichenkoKCK I was not able to reproduce the described behavior (I'm on Linux: I could delete the file even before the line `dbfWriter.close()`!!). However you are right : the memo file wasn't properly closed. I tried to fix that in the latest commit. Could you check it please ?

**Comment by ChuichenkoKCK** [comment] 2021-05-31 06:25
It works. Bug was fixed. Thanks!

**Comment by jferard** [comment] 2021-05-31 20:27
Thank you. I close the issue.

**Closed by jferard** 2021-05-31 20:27 UTC
Labels: bug
